CREATE TABLE orders (
    id BIGSERIAL PRIMARY KEY NOT NULL,
    book_isbn VARCHAR(255) NOT NULL,
    book_name VARCHAR(255) NOT NULL,
    quantity INT NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 0)